main: "jp.jyn.moreenjoy.ridenow.Main"
name: "RideNow"
version: "${project.version}"
website: "${project.parent.url}"
author: "HimaJyun( https://jyn.jp/ )"
description: "${project.description}"
api-version: "${spigot.api-version}"

commands:
  boat:
    description: "Ride boat."
    usage: "/<command>"
  minecart:
    description: "Ride minecart."
    usage: "/<command>"

permissions:
  moreenjoy.*:
    default: false
    children:
      moreenjoy.ridenow.minecart: true
      moreenjoy.ridenow.boat: true
  moreenjoy.ridenow.minecart:
    default: true
  moreenjoy.ridenow.boat:
    default: true
