AnyHat:
  enable: true

NoVoid:
  enable: true
  exclude:
    - "world_the_end"

RideNow:
  enable: true

InfinityFirework:
  enable: true

ImmutableSpawner:
  enable: true

CrystalGuard:
  enable: true
  damage:
    - "world_the_end"
  break: [ ]

ByeByeWither:
  enable: true
  wither:
    - "world_nether"
    - "world_the_end"
  dragon:
    - "world_the_end"

MoreColor:
  enable: true
  marker: "&r"
  # always, marker, false
  sign: always
  book: marker

EditSign:
  enable: true
  error: "&cInvalid argument!!"
  ready: "Ready to edit: {value}"
  # If true, break the sign and edit it.
  # Suitable for coexistence with plugins with protection features.
  safety: true

JoinMessage:
  enable: true
  join: "&e{player} joined the game"
  quit: "&e{player} left the game"

DocklessVehicle:
  enable: true
  boat: player # always(true)/player(no-player)/empty(only-empty)/first(is-first)/false
  minecart: true
  sendToInventory: true
  ready: "Please right-click vehicle."
  stop: "Automatic collection has been stopped."
  start: "Automatic collection has been restarted."

ThisWorld:
  enable: true
  unavailable: "&cNot available in this world."
  # unit: tick (1/20 second = 50ms)
  # chat and actionbar have no effect.
  time:
    fadein: 10
    stay: 35
    fadeout: 10
    delay: 0
  title:
    world:
      title: "&2World"
      subtitle: "Our world."
      actionbar: "Don't mining in this world."
      # available multiple lines.
      chat: [ "Don't griefing!", "Have fun!" ]
      # available time override.
      fadein: 10
      stay: 35
      fadeout: 10
      delay: 0
    world_nether:
      title: "&cNether"
      subtitle: "world_nether"
    world_the_end:
      title: "&8The End"
      subtitle: "&kworld_the_end"
      actionbar: "vs EnderDragon"

LoreBook:
  enable: true
  notEnough: "&cNot enough experience points!"
  onlyDurable: false
  # Due to Bukkit restrictions, the required experience points will not be displayed on the anvil.
  experience: 0
  maxLength: 24
  maxLine: 12

OpenNow:
  enable: true
  shulker: true
  ender: true
  # right/shift-right/left/shift-left/false
  placeOpen: left
  enderOnlyOne: true
  lore: "Opened by {player}"

# //*<!-- syntax -->*/
# &0->Black(#000000)
# &1->Dark Blue(#0000AA)
# &2->Dark Green(#00AA00)
# &3->Dark Aqua(#00AAAA)
# &4->Dark Red(#AA0000)
# &5->Purple(#AA00AA)
# &6->Gold(#FFAA00)
# &7->Gray(#AAAAAA)
# &8->Dark Gray(#555555)
# &9->Blue(#5555FF)
# &a->Green(#55FF55)
# &b->Aqua(#55FFFF)
# &c->Red(#FF5555)
# &d->Light Purple(#FF55FF)
# &e->Yellow(#FFFF55)
# &f->White(#FFFFFF)
# &k->Obfuscated
# &l->Bold
# &m->Strikethrough
# &n->Underline
# &o->Italic
# &r->Reset
# #rrggbb(or #rgb)->Hex color
# &->escape
