main: "jp.jyn.moreenjoy.MoreEnjoy"
name: "MoreEnjoy"
version: "${project.version}"
website: "${project.parent.url}"
author: "HimaJyun( https://jyn.jp/ )"
description: "${project.description}"
api-version: "${spigot.api-version}"

commands:
  # all-in-one
  moreenjoy-reload:
    description: "reload config."
    usage: "/<command>"
    permission: "moreenjoy.reload"
  # AnyHat
  hat:
    usage: "/<command>"
  # EditSign
  edit:
    usage: "/<command> <line> <content>"
  # DocklessVehicle
  dockless:
    usage: "/<command> [true/false]"
  # RideNow
  boat:
    usage: "/<command>"
  minecart:
    usage: "/<command>"
  # ThisWorld
  thisworld:
    usage: "/<command>"

permissions:
  moreenjoy.*:
    default: false
    children:
      moreenjoy.reload: true
      moreenjoy.anyhat.hat: true
      moreenjoy.byebyewither.dragon: true
      moreenjoy.docklessvehicle.dock: true
      moreenjoy.editsign.edit: true
      moreenjoy.immutablespawner.allow: true
      moreenjoy.lorebook.use: true
      moreenjoy.ridenow.minecart: true
      moreenjoy.ridenow.boat: true
      moreenjoy.thisworld.show: true
  moreenjoy.reload:
    default: op
  # AnyHat
  moreenjoy.anyhat.hat:
    default: true
  # ByeByeWither
  moreenjoy.byebyewither.dragon:
    default: op
  # DocklessVehicle
  moreenjoy.docklessvehicle.dock:
    default: true
  # EditSign
  moreenjoy.editsign.edit:
    default: true
  # ImmutableSpawner
  moreenjoy.immutablespawner.allow:
    default: op
  # LoreBook
  moreenjoy.lorebook.use:
    default: true
  # RideNow
  moreenjoy.ridenow.minecart:
    default: true
  moreenjoy.ridenow.boat:
    default: true
  # ThisWorld
  moreenjoy.thisworld.show:
    default: true
