main: "jp.jyn.moreenjoy.MoreEnjoy"
name: "MoreEnjoy"
version: "${project.version}"
website: "${project.parent.url}"
author: "HimaJyun( https://jyn.jp/ )"
description: "${project.description}"
api-version: "${spigot.api-version}"

commands:
  hat:
    description: "Wear everything on your head."
    usage: "/<command>"
    aliases: [ "moreenjoy-anyhat" ]
  boat:
    description: "Ride boat."
    usage: "/<command>"
  minecart:
    description: "Ride minecart."
    usage: "/<command>"
  edit:
    description: "Edit sign."
    usage: "/<command> <line> <content>"
  dockless:
    description: "Stop automatic collection."
    usage: "/<command> [true/false]"

# TODO: 権限調整
permissions:
  moreenjoy.*:
    default: false
    children:
      moreenjoy.anyhat.hat: true
      moreenjoy.ridenow.minecart: true
      moreenjoy.ridenow.boat: true
      moreenjoy.immutablespawner.allow: true
      moreenjoy.byebyewither.dragon: true
      moreenjoy.editsign.edit: true
      moreenjoy.docklessvehicle.dock: true
  # AnyHat
  moreenjoy.hat:
    default: false
    children:
      moreenjoy.anyhat.hat: true
  moreenjoy.anyhat.*:
    default: false
    children:
      moreenjoy.anyhat.hat: true
  moreenjoy.anyhat.hat:
    description: "Allow use of /hat command."
    default: true
  # RideNow
  moreenjoy.minecart:
    default: false
    children:
      moreenjoy.ridenow.minecart: true
  moreenjoy.boat:
    default: false
    children:
      moreenjoy.ridenow.boat: true
  moreenjoy.ridenow.*:
    default: false
    children:
      moreenjoy.ridenow.minecart: true
      moreenjoy.ridenow.boat: true
  moreenjoy.ridenow.minecart:
    default: true
  moreenjoy.ridenow.boat:
    default: true
  # ImmutableSpawner
  moreenjoy.immutablespawner.allow:
    default: op
  # ByeByeWither
  moreenjoy.byebyewither.dragon:
    default: op
  # EditSign
  moreenjoy.edit:
    default: false
    children:
      moreenjoy.editsign.edit: true
  moreenjoy.editsign.edit:
    default: true
  # DocklessVehicle
  moreenjoy.dock:
    default: false
    children:
      moreenjoy.docklessvehicle.dock: true
  moreenjoy.docklessvehicle.dock:
    default: true
