main: "jp.jyn.moreenjoy.slabcombine.Main"
name: "SlabCombine"
version: "${project.version}"
website: "${project.parent.url}"
author: "HimaJyun( https://jyn.jp/ )"
description: "${project.description}"
api-version: "${spigot.api-version}"
