# always(true)/player(no-player)/empty(only-empty)/first(is-first)/false
boat: player
minecart: true
sendToInventory: true
ready: "Please right-click vehicle."
stop: "Automatic collection has been stopped."
start: "Automatic collection has been restarted."
